"""
DEVATTECH-89: DS-1 -- committed, seeded synthetic fraud training dataset
generator.

Extracted out of train_fraud_xgb.py so dataset generation is its own
reusable, independently runnable unit (AC #1: "DS-1 must be generated by
a committed seeded script, not manual/random external data").

Fully deterministic given (n_rows, fraud_rate, seed) -- no external data,
no network calls, no dependency on the running app or database. Safe to
run standalone:

    python ml/fraud/generate_ds1.py

writes ml/fraud/data/ds1.csv for manual inspection (not required by
train_fraud_xgb.py, which calls generate_ds1() directly rather than
reading a file -- DS-1 is reproduced from the seed on every training run,
so the CSV itself does not need to be committed to stay reproducible).
"""
import numpy as np
import pandas as pd

DS1_SEED = 42
DS1_N_ROWS = 12_000
DS1_FRAUD_RATE = 0.05

# Order matters -- must match app/services/fraud_scoring.py's
# _compute_xgb_features() return order exactly. Do not reorder without
# updating that function and re-running training.
FEATURE_ORDER = [
    "amount",
    "amount_to_user_avg_ratio",
    "is_new_recipient",
    "hour_of_day",
    "day_of_week",
    "sender_tx_count_30d",
    "currency_match",
]


def _night_weighted_hour_probs() -> np.ndarray:
    """Fraud is somewhat more likely at odd/night hours (00:00-05:00)."""
    probs = np.ones(24)
    probs[0:6] *= 3.0
    return probs / probs.sum()


def generate_ds1(
    n_rows: int = DS1_N_ROWS,
    fraud_rate: float = DS1_FRAUD_RATE,
    seed: int = DS1_SEED,
) -> pd.DataFrame:
    """
    DS-1: synthetic transaction dataset for training the fraud model.
    Fraudulent rows are generated with systematically different feature
    distributions (larger amounts relative to the sender's average, more
    likely to be a new recipient, skewed toward night hours, low prior
    transaction history, more currency mismatches) so there is a
    learnable signal. This is synthetic data for standing up the
    pipeline -- not a claim about real Lebanese transaction patterns.
    Replace with real labeled data (once available) by swapping this
    function's output for a DataFrame with the same columns.

    Deterministic: the same (n_rows, fraud_rate, seed) always produces
    the same dataset, byte-for-byte.
    """
    rng = np.random.default_rng(seed)
    n_fraud = int(round(n_rows * fraud_rate))
    n_legit = n_rows - n_fraud

    legit = pd.DataFrame({
        "amount": rng.lognormal(mean=4.5, sigma=1.0, size=n_legit),
        "amount_to_user_avg_ratio": rng.lognormal(mean=0.0, sigma=0.3, size=n_legit),
        "is_new_recipient": rng.choice([0, 1], size=n_legit, p=[0.85, 0.15]),
        "hour_of_day": rng.integers(0, 24, size=n_legit),
        "day_of_week": rng.integers(0, 7, size=n_legit),
        "sender_tx_count_30d": rng.poisson(lam=8, size=n_legit),
        "currency_match": rng.choice([0, 1], size=n_legit, p=[0.05, 0.95]),
        "is_fraud": 0,
    })

    fraud = pd.DataFrame({
        "amount": rng.lognormal(mean=6.0, sigma=1.3, size=n_fraud),
        "amount_to_user_avg_ratio": rng.lognormal(mean=1.5, sigma=0.8, size=n_fraud),
        "is_new_recipient": rng.choice([0, 1], size=n_fraud, p=[0.25, 0.75]),
        "hour_of_day": rng.choice(np.arange(24), size=n_fraud, p=_night_weighted_hour_probs()),
        "day_of_week": rng.integers(0, 7, size=n_fraud),
        "sender_tx_count_30d": rng.poisson(lam=2, size=n_fraud),
        "currency_match": rng.choice([0, 1], size=n_fraud, p=[0.4, 0.6]),
        "is_fraud": 1,
    })

    df = pd.concat([legit, fraud], ignore_index=True)
    df = df.sample(frac=1.0, random_state=seed).reset_index(drop=True)

    df["amount"] = df["amount"].round(2)
    df["amount_to_user_avg_ratio"] = df["amount_to_user_avg_ratio"].round(3)
    df["sender_tx_count_30d"] = df["sender_tx_count_30d"].clip(lower=0)

    return df


if __name__ == "__main__":
    from pathlib import Path

    df = generate_ds1()
    out_dir = Path(__file__).resolve().parent / "data"
    out_dir.mkdir(exist_ok=True)
    out_path = out_dir / "ds1.csv"
    df.to_csv(out_path, index=False, encoding="utf-8")
    print(
        f"Generated DS-1: {len(df)} rows, {int(df['is_fraud'].sum())} fraud "
        f"({df['is_fraud'].mean():.2%}) -> {out_path}"
    )
