"""add exchange audit log table

Revision ID: 61faf64c5f63
Revises: 266e7be163e5
Create Date: 2026-07-02 20:41:46.883528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '61faf64c5f63'
down_revision: Union[str, Sequence[str], None] = '266e7be163e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.String(length=36), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('converted_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_audit_logs_exchange_id'), 'exchange_audit_logs', ['exchange_id'], unique=True)
    op.create_index(op.f('ix_exchange_audit_logs_id'), 'exchange_audit_logs', ['id'], unique=False)
    # NOTE: autogenerate against a shared dev DB also emitted drops of
    # user_sessions and users.passcode_hash (owned by the auth feature).
    # Those were false positives and must not run here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_audit_logs_id'), table_name='exchange_audit_logs')
    op.drop_index(op.f('ix_exchange_audit_logs_exchange_id'), table_name='exchange_audit_logs')
    op.drop_table('exchange_audit_logs')
    # ### end Alembic commands ###
