"""add rule_triggered to transactions (DEVATTECH-87)

Revision ID: a1b2c3d4e5f6
Revises: fef1258ad3aa
Create Date: 2026-07-03 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = 'fef1258ad3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # DEVATTECH-87: rule-based fraud fallback layer. Written by hand rather
    # than autogenerated -- local migration history is ahead of the shared
    # Neon DB's current revision (DB is at 266e7be163e5; this branch's head
    # is fef1258ad3aa), so `alembic revision --autogenerate` can't safely
    # diff against actual DB state right now. This migration ONLY adds
    # rule_triggered -- no other schema changes.
    op.add_column(
        'transactions',
        sa.Column('rule_triggered', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('transactions', 'rule_triggered')
